/*
 * This source file was generated by the Gradle 'init' task
 */
package weather.app.gradle;

public class App {

    public static void main(String[] args) {
        ApiUtilities newRequest = new ApiUtilities();
        Object response = newRequest.getRequest("Chisinau", "Forecast", 2);
        System.out.println(response);
    }
}
